<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_concat(, , kopi, , )_rounded-lg h-full w-full</name>
   <tag></tag>
   <elementGuidId>6da9c430-bfe4-4e8b-8646-4fd610e41b72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/main/div/div/div[2]/div/div[2]/div/div[3]/div/div/div/div/div[2]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.rounded-lg.h-full.w-full</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>partner image</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rounded-lg h-full w-full</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://minio.pijarmahir.id/course/PM-PRA-CRI-063.jpg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;flex flex-col min-h-screen&quot;]/main[@class=&quot;pt-24 flex-1&quot;]/div[1]/div[@class=&quot;justify-center pb-24&quot;]/div[@class=&quot;flex justify-center w-full my-8&quot;]/div[@class=&quot;flex justify-between flex-col md:flex-row w-full md:max-w-screen-md lg:max-w-screen-lg&quot;]/div[@class=&quot;w-full px-2&quot;]/div[@class=&quot;w-full px-2&quot;]/div[@class=&quot;my-6&quot;]/div[1]/div[@class=&quot;items-center text-center rounded-lg w-full&quot;]/div[@class=&quot;flex md:h-auto&quot;]/div[@class=&quot;rounded-lg mb-2 rounded-br-lg cursor-pointer&quot;]/div[@class=&quot;w-16 md:w-60 h-12 md:h-36&quot;]/img[@class=&quot;rounded-lg h-full w-full&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/div/div/div[2]/div/div[2]/div/div[3]/div/div/div/div/div[2]/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='partner image']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'partner image' and @src = 'https://minio.pijarmahir.id/course/PM-PRA-CRI-063.jpg']</value>
   </webElementXpaths>
</WebElementEntity>
